### PR TITLE
Made buttons text (submit, clear, ..) unselectable

### PR DESCRIPTION
**Pull request by JordyGit**

### CODE REVIEW

**Comment by benitolopez** [comment]
Please compile the CSS files the next time.

**Comment by JordyGit** [comment]
I have no experience with compiling scss, I usually program just css so I don't need to do so. I'll check it out next time.

**Comment by JordyGit** [comment]
Could be something a pipeline does, no?

**Comment by benitolopez** [comment]
> Could be something a pipeline does, no?

No, you can't compile sass files automatically in GitHub. It must be compiled in your computer.

**Comment by JordyGit** [comment]
A fast google search makes me thing it it possible, but maybe it's not worth the investment of time if you are used to build it locally :) 
([https://github.com/marketplace/actions/sass-build](https://github.com/marketplace/actions/sass-build))

**Pull request merged**
