### PR TITLE
fix i18n with formats `MMM` and `dddd`

### PR DESCRIPTION
**Pull request by thomasleveil**

### CODE REVIEW

**Comment by benitolopez** [comment]
Need some time to consider this PR. The purpose of this plugin is to maintain the code and the features simple as much as possible. I'm not sure that the introduction of two different ways to set the names (short and long) is a good thing. Users already have the possibility to pass their preferred text to the `day-names` and `month-names` properties.

Also, this will break existent installations, requiring a manual upgrade.

For me, there's no need to have two different formats. But I may be wrong.

**Comment by thomasleveil** [comment]
My intent is not to introduce a new way to provide i18n strings, but to fix an issue whenever a user tries to use the `MMM` or `dddd` formats.

To witness the issue, checkout this commit 20eb532 (`git fetch upstream pull/15/head:pr-15; git checkout 
20eb532`), load the demo page and play with the picker from `demo14`: We end up with English day names and short month names instead of Italian.

image

**Comment by thomasleveil** [comment]
To preserve backward compatibility, option `i18n['day-names']` could stay as it is, and `i18n['day-names-full']` introduced. It will make it a bit awkward for new-comers, but be backward compatible.

**Comment by benitolopez** [comment]
Yes, you're right. 

So now the problem is about the property name. Your PR is theoretically correct, we should use `i18n['day-names-short']` for short names, in the same way we use  `i18n['month-names']` (without a suffix) for long names. `i18n['day-names-full']` or `i18n['day-names-long']` will probably create some confusion.

But at the same time, this change will not be backward compatible. 

My personal opinion is that we can use `i18n['day-names-short']`, add some info in the readme and change the project version to 3.

**Comment by benitolopez** [comment]
Checked your PR locally but there are some errors. Check the attached screenshot.

screen shot 2017-11-15 at 12 52 53 am

**Comment by benitolopez** [comment]
Ok, the error is in the format you used in the demo. It should be `dddd D MMM YYYY`, not `dddd d MMM YYYY`. I will fix it myself.

**Pull request merged**
